import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor, fireEvent, act } from '@testing-library/react';
import { findModule, cleanFxName, resolveParam, type ModuleControl } from '../components/grid/modules';
import { yutaniModule } from '../components/grid/yutani';
import { midiArpModule } from '../components/grid/midiarp';
import { GridView, fitScaleFor, maxRowsFor, shapeFor } from '../components/grid/GridView';
import { NoteGrid, HelpLabel } from '../components/grid/widgets';
import type { Track, FxInfo, FxParam } from '../hooks/useReaper';

// ── Module matching ──────────────────────────────────────────

describe('grid module matching', () => {
  it('strips REAPER format prefixes', () => {
    expect(cleanFxName('JS: Chorus')).toBe('Chorus');
    expect(cleanFxName('VST3: ReaEQ (Cockos)')).toBe('ReaEQ (Cockos)');
    expect(cleanFxName('Chorus')).toBe('Chorus');
  });

  it('finds the Chorus module however REAPER prefixes it', () => {
    expect(findModule('JS: Chorus')).not.toBeNull();
    expect(findModule('Chorus')).not.toBeNull();
  });

  it('does not match unrelated plugins', () => {
    expect(findModule('JS: ReaEQ')).toBeNull();
    expect(findModule('VST3: Pro-Q 3')).toBeNull();
    // Guard against a loose substring match picking up other chorus-ish names
    expect(findModule('JS: Chorus-Ensemble Deluxe')).toBeNull();
  });

  // Controls reference JSFX slider numbers, 1-based as declared in the source.
  // Getting one wrong silently drives a different control, so pin them.
  it('references the right Chorus sliders', () => {
    const m = findModule('JS: Chorus')!;
    const bySlider: Record<string, number> = {};
    for (const panel of m.panels) {
      for (const c of panel.controls) bySlider[c.label] = c.slider;
    }
    expect(bySlider).toEqual({
      Time: 1,    // slider1 Chorus Length (ms)
      Voices: 2,  // slider2 Number Of Voices
      Rate: 3,    // slider3 Rate (Hz)
      Depth: 4,   // slider4 Pitch Fudge Factor
      Wet: 5,     // slider5 Wet Mix (dB)
      Dry: 6,     // slider6 Dry Mix (dB)
    });
  });

  it('offers one segmented option per voice', () => {
    const m = findModule('Chorus')!;
    const seg = m.panels
      .flatMap((p) => p.controls)
      .find((c) => c.kind === 'segmented');
    expect(seg).toBeDefined();
    expect(seg!.kind === 'segmented' && seg!.options.map((o) => o.value))
      .toEqual([1, 2, 3, 4, 5, 6, 7, 8]);
  });
});

// ── Yutani ───────────────────────────────────────────────────
//
// Generated by tools/jsfx_module_gen.py from the patched copy, so these guard
// the generator's output rather than hand-written code.

describe('Yutani module', () => {
  const yutani = findModule('JS: Yutani Mono Bass Synth [Saike] (BETA) [Spidercrab]');

  it('matches the patched copy', () => {
    expect(yutani).not.toBeNull();
    expect(yutani!.title).toBe('Yutani');
  });

  it('covers all of the plugin\'s sections', () => {
    expect(yutani!.panels).toHaveLength(22);
    const labels = yutani!.panels.map((p) => p.label);
    expect(labels).toContain('OSCILLATOR 1');
    expect(labels).toContain('FILTER');
    expect(labels).toContain('NOISE');
    // Trailing whitespace in the plugin's own title strings shouldn't leak out
    expect(labels.every((l) => l === l.trim())).toBe(true);
  });

  // Two controls on one slider means the second silently shadows the first.
  it('never references the same slider twice', () => {
    const sliders = yutani!.panels.flatMap((p) => p.controls.map((c) => c.slider));
    expect(new Set(sliders).size).toBe(sliders.length);
  });

  // Without expect the resolver falls back to a raw index, which is exactly
  // what can't be trusted for a plugin with gapped slider numbering.
  it('gives every control a name to verify against', () => {
    const missing = yutani!.panels
      .flatMap((p) => p.controls)
      .filter((c) => !c.expect);
    expect(missing).toEqual([]);
  });

  it('files Oscillator 2 Shape under Oscillator 2', () => {
    // The generator puts it in Oscillator 1 — a PWM check near that panel
    // boundary mentions both SELECT constants — so it's corrected by hand.
    const osc2 = yutani!.panels.find((p) => p.label === 'OSCILLATOR 2')!;
    expect(osc2.controls.some((c) => c.expect === 'Oscillator 2 Shape')).toBe(true);
    const osc1 = yutani!.panels.find((p) => p.label === 'OSCILLATOR 1')!;
    expect(osc1.controls.some((c) => c.expect === 'Oscillator 2 Shape')).toBe(false);
  });

  // Integer ranges that declare no labels would otherwise render as knobs;
  // the labels come from the plugin's drawSelectionButton calls.
  it('recovers selection-button labels the declarations omit', () => {
    const sub = yutani!.panels
      .flatMap((p) => p.controls)
      .find((c) => c.expect === 'SubOsc Shape');
    expect(sub?.kind).toBe('segmented');
    expect(sub!.kind === 'segmented' && sub!.options.map((o) => o.label))
      .toEqual(['Sine', 'Odd', 'Even', 'Tri', 'Mud']);
  });
});

// ── Parameter resolution ─────────────────────────────────────
//
// A JSFX slider number is not necessarily REAPER's parameter index. Yutani
// declares sliders 1-66, 71-73 and 80-81, so whether REAPER compacts those
// gaps or preserves them shifts everything past slider 66. The resolver
// treats the slider number as a guess and confirms it by name.

describe('resolveParam', () => {
  const ctl = (slider: number, expect_?: string): ModuleControl =>
    ({ kind: 'knob', slider, expect: expect_, label: 'x' });

  it('uses the slider number when the name confirms it', () => {
    const params = [
      { index: 0, name: 'Alpha' }, { index: 1, name: 'Beta' }, { index: 2, name: 'Gamma' },
    ];
    expect(resolveParam(params, ctl(2, 'Beta'))?.index).toBe(1);
  });

  // Gaps preserved: slider 71 sits at index 70.
  it('finds the parameter by name when the index is shifted', () => {
    const params = [
      { index: 0, name: 'Alpha' }, { index: 66, name: 'AP frequency' },
    ];
    expect(resolveParam(params, ctl(71, 'AP frequency'))?.index).toBe(66);
  });

  // Yutani has three parameters called "Detune [semitones]".
  it('picks the nearest candidate when a label repeats', () => {
    const params = [
      { index: 19, name: 'Detune [semitones]' },
      { index: 21, name: 'Detune [semitones]' },
      { index: 23, name: 'Detune [semitones]' },
    ];
    expect(resolveParam(params, ctl(22, 'Detune [semitones]'))?.index).toBe(21);
  });

  it('returns nothing when the parameter is absent', () => {
    expect(resolveParam([{ index: 0, name: 'Alpha' }], ctl(9, 'Missing'))).toBeUndefined();
  });

  it('falls back to the raw index when no name is given', () => {
    const params = [{ index: 0, name: 'Alpha' }, { index: 1, name: 'Beta' }];
    expect(resolveParam(params, ctl(2))?.index).toBe(1);
  });
});

// ── GridView ─────────────────────────────────────────────────

const tracks: Track[] = [
  { index: 0, name: 'Gtr', trackNumber: 1, selected: true, muted: false, soloed: false, armed: false, recMode: 0, volume: 0.8, pan: 0 },
];

const chorusParams: FxParam[] = [
  { index: 0, name: 'Chorus Length (ms)', value: 15, min: 1, max: 250, mid: 125 },
  { index: 1, name: 'Number Of Voices', value: 1, min: 1, max: 8, mid: 4 },
  { index: 2, name: 'Rate (Hz)', value: 0.5, min: 0.1, max: 16, mid: 8 },
  { index: 3, name: 'Pitch Fudge Factor', value: 0.7, min: 0, max: 1, mid: 0.5 },
  { index: 4, name: 'Wet Mix (dB)', value: -6, min: -100, max: 12, mid: -44 },
  { index: 5, name: 'Dry Mix (dB)', value: -6, min: -100, max: 12, mid: -44 },
];

function renderGrid(fx: FxInfo[], selectedTrack: number | null = 0) {
  const getTrackFx = vi.fn().mockResolvedValue(fx);
  const getFxParams = vi.fn().mockResolvedValue({
    params: chorusParams, total: chorusParams.length, offset: 0, limit: 64,
  });
  const setFxParam = vi.fn().mockResolvedValue({ payload: {} });
  render(
    <GridView
      tracks={tracks}
      selectedTrack={selectedTrack}
      getTrackFx={getTrackFx}
      getFxParams={getFxParams}
      setFxParam={setFxParam}
    />,
  );
  return { getTrackFx, getFxParams, setFxParam };
}

describe('GridView', () => {
  it('prompts for a track when none is selected', () => {
    renderGrid([], null);
    expect(screen.getByText('No track selected')).toBeDefined();
  });

  it('says so when the track has no FX', async () => {
    renderGrid([]);
    await waitFor(() => expect(screen.getByText(/has no FX/)).toBeDefined());
  });

  // The FX tab stays the way to reach plugins without a layout, so Grid should
  // say that rather than appear broken.
  // Every plugin now appears: those without a hand-authored module get
  // panels generated from their parameter list, which is worse than a real
  // layout but far better than the plugin being unreachable.
  it('falls back to generated panels for a plugin with no module', async () => {
    renderGrid([{ index: 0, name: 'VST3: ReaEQ' }, { index: 1, name: 'JS: ReaComp' }]);
    await waitFor(() =>
      expect(screen.getAllByTestId('grid-device-title')).toHaveLength(2));
    expect(screen.getAllByTestId('grid-device-title').map((e) => e.textContent))
      .toEqual(['ReaEQ', 'ReaComp']);
  });

  it('renders a device for a plugin with a module', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() =>
      expect(screen.getByTestId('grid-device-title').textContent).toBe('Chorus'));
    // Panels
    expect(screen.getByText('Voices')).toBeDefined();
    expect(screen.getByText('Motion')).toBeDefined();
    expect(screen.getByText('Output')).toBeDefined();
  });

  it('renders each control as the type the module asks for', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);

    // Knobs and faders expose slider semantics
    await waitFor(() => {
      expect(screen.getByLabelText('Rate')).toBeDefined();
    });
    expect(screen.getByLabelText('Depth')).toBeDefined();
    expect(screen.getByLabelText('Time')).toBeDefined();
    expect(screen.getByLabelText('Wet')).toBeDefined();
    expect(screen.getByLabelText('Dry')).toBeDefined();

    // Voice count is eight buttons, not a slider — the whole point of the module
    const one = screen.getByRole('button', { name: '1' });
    expect(one.getAttribute('aria-pressed')).toBe('true');
    expect(screen.getByRole('button', { name: '8' })).toBeDefined();
  });

  it('formats values with the module’s units rather than raw numbers', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByText('0.50 Hz')).toBeDefined());
    expect(screen.getByText('70%')).toBeDefined();   // 0.7 depth
    expect(screen.getByText('15 ms')).toBeDefined();
    expect(screen.getAllByText('-6 dB')).toHaveLength(2); // wet + dry
  });

  // Navigation lives in the bottom strip rather than the device surface, so
  // controls don't have to share the screen with a pan gesture.
  it('provides a strip to navigate between devices', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByTestId('grid-strip')).toBeDefined());
    // One chip per device, tappable to jump
    expect(screen.getByRole('button', { name: 'Chorus' })).toBeDefined();
  });

  it('does not let the device surface pan by touch', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    const scroller = await waitFor(() => screen.getByTestId('grid-scroller'));
    // touch-none: the strip owns navigation, so a stray swipe here must not
    // scroll the surface out from under a knob mid-drag.
    expect(scroller.className).toContain('touch-none');
  });

  // A drag arrives as many small pointermove events. The drag handler used to
  // report per-event deltas while the widget re-derived from its current
  // value, so each event landed at roughly the same place and the control
  // never travelled more than a single step — it "barely worked".
  it('accumulates a multi-event drag rather than applying one step', async () => {
    const { setFxParam } = renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    const rate = await waitFor(() => screen.getByLabelText('Rate'));

    // Rate spans 0.1–16 from a start of 0.5. Dragging up 95px is half the
    // 190px travel, so it should land near the middle of the range.
    fireEvent.pointerDown(rate, { clientX: 0, clientY: 300, pointerId: 1, button: 0 });
    for (let y = 295; y >= 205; y -= 5) {
      fireEvent.pointerMove(window, { clientX: 0, clientY: y, pointerId: 1 });
    }
    fireEvent.pointerUp(window, { clientX: 0, clientY: 205, pointerId: 1 });

    await waitFor(() => expect(setFxParam).toHaveBeenCalled());
    const sent = setFxParam.mock.calls.map((c) => c[3] as number);
    const furthest = Math.max(...sent);

    // Half of 15.9 added to 0.5 is ~8.5. Anything near the 0.5 start means the
    // drag stopped accumulating.
    expect(furthest).toBeGreaterThan(6);
  });

  it('drags the whole range without releasing', async () => {
    const { setFxParam } = renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    const depth = await waitFor(() => screen.getByLabelText('Depth'));

    // Depth is 0–1, starting at 0.7. A full 190px upward drag must reach the top.
    fireEvent.pointerDown(depth, { clientX: 0, clientY: 400, pointerId: 1, button: 0 });
    for (let y = 390; y >= 200; y -= 10) {
      fireEvent.pointerMove(window, { clientX: 0, clientY: y, pointerId: 1 });
    }
    fireEvent.pointerUp(window, { clientX: 0, clientY: 200, pointerId: 1 });

    await waitFor(() => expect(setFxParam).toHaveBeenCalled());
    const sent = setFxParam.mock.calls.map((c) => c[3] as number);
    expect(Math.max(...sent)).toBeCloseTo(1, 2);
  });

  it('shows every plugin, titling each by its cleaned name', async () => {
    renderGrid([
      { index: 0, name: 'VST3: ReaEQ' },
      { index: 1, name: 'JS: Chorus' },
      { index: 2, name: 'VST3: Pro-Q 3' },
    ]);
    await waitFor(() => expect(screen.getAllByTestId('grid-device-title')).toHaveLength(3));
    expect(screen.getAllByTestId('grid-device-title').map((e) => e.textContent))
      .toEqual(['ReaEQ', 'Chorus', 'Pro-Q 3']);
    expect(screen.getByText(/3 devices/)).toBeDefined();
  });
});

// ── Modulation modes and panel switches ──────────────────────
//
// Yutani keeps three depths on most knobs — how far velocity, the mod wheel
// and the free LFO move them — and reaches them by latching a mode and
// dragging the parent knob. Rendering them as siblings instead tripled the
// control count and lost which knob each belonged to.

/** Every parameter the Yutani module references, named as it expects. */
function yutaniParams(): FxParam[] {
  const out: FxParam[] = [];
  const add = (slider: number, name: string, value: number, min: number, max: number) => {
    if (!out.some((p) => p.index === slider - 1)) {
      out.push({ index: slider - 1, name, value, min, max, mid: (min + max) / 2 });
    }
  };
  for (const panel of yutaniModule.panels) {
    if (panel.enable) add(panel.enable.slider, panel.enable.expect!, 1, 0, 1);
    for (const c of panel.controls) {
      add(c.slider, c.expect!, 0.5, 0, 1);
      for (const m of c.modifiers ?? []) add(m.slider, m.expect!, 0, -1, 1);
    }
  }
  return out;
}

const presetNames = ['Init', 'Reese', 'Hoover', 'Sub Rumble'];

function renderYutani() {
  const params = yutaniParams();
  const setFxParam = vi.fn().mockResolvedValue({ payload: {} });
  const getFxParams = vi.fn().mockResolvedValue({
    params, total: params.length, offset: 0, limit: 256,
  });
  const getFxPreset = vi.fn().mockResolvedValue({
    presetIndex: 1, presetName: 'Reese', numPresets: presetNames.length,
  });
  const setFxPreset = vi.fn().mockImplementation((_t, _f, idx) => Promise.resolve({
    presetIndex: idx, presetName: presetNames[idx], numPresets: presetNames.length,
  }));
  const getAllFxPresetNames = vi.fn().mockResolvedValue({
    presetNames, currentIndex: 1,
  });
  render(
    <GridView
      tracks={tracks}
      selectedTrack={0}
      getTrackFx={vi.fn().mockResolvedValue([{ index: 0, name: 'JS: Yutani [Spidercrab]' }])}
      getFxParams={getFxParams}
      setFxParam={setFxParam}
      getFxPreset={getFxPreset}
      setFxPreset={setFxPreset}
      getAllFxPresetNames={getAllFxPresetNames}
    />,
  );
  return { setFxParam, getFxParams, setFxPreset, getAllFxPresetNames, params };
}

describe('Yutani modulation depths', () => {
  const controls = yutaniModule.panels.flatMap((p) => p.controls);

  it('folds depths into the knob they are edited through', () => {
    const withMods = controls.filter((c) => c.modifiers?.length);
    expect(withMods.length).toBeGreaterThan(20);
    // Every modifier hangs off a knob: a depth on a discrete choice is
    // meaningless, and the drag gesture only exists on continuous controls.
    expect(withMods.every((c) => c.kind === 'knob')).toBe(true);
  });

  it('never lists a depth as a control in its own right', () => {
    const asControl = new Set(controls.map((c) => c.slider));
    const asDepth = controls.flatMap((c) => c.modifiers ?? []).map((m) => m.slider);
    expect(asDepth.filter((s) => asControl.has(s))).toEqual([]);
  });

  it('gives each knob at most one depth per mode', () => {
    for (const c of controls) {
      const kinds = (c.modifiers ?? []).map((m) => m.kind);
      expect(kinds.length).toBe(new Set(kinds).size);
    }
  });

  it('keeps section switches out of the control list', () => {
    const panels = yutaniModule.panels.filter((p) => p.enable);
    expect(panels.length).toBeGreaterThan(0);
    for (const p of panels) {
      expect(p.controls.some((c) => c.slider === p.enable!.slider)).toBe(false);
    }
  });
});

describe('GridView modulation modes', () => {
  it('offers a mode switch only for devices that have depths', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('group', { name: 'Modulation mode' })).toBeDefined());
    for (const label of ['VEL', 'MOD', 'LINK']) {
      expect(screen.getByRole('button', { name: label })).toBeDefined();
    }
  });

  it('leaves Chorus without one, having nothing to modulate', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByTestId('grid-device-title')).toBeDefined());
    expect(screen.queryByRole('group', { name: 'Modulation mode' })).toBeNull();
  });

  it('latches on tap and releases on a second tap', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('button', { name: 'VEL' })).toBeDefined());
    const vel = screen.getByRole('button', { name: 'VEL' });

    expect(vel.getAttribute('aria-pressed')).toBe('false');
    fireEvent.click(vel);
    expect(vel.getAttribute('aria-pressed')).toBe('true');
    fireEvent.click(vel);
    expect(vel.getAttribute('aria-pressed')).toBe('false');
  });

  it('retargets a modulatable knob at its depth while a mode is latched', async () => {
    renderYutani();
    const gain = yutaniModule.panels
      .flatMap((p) => p.controls)
      .find((c) => c.modifiers?.some((m) => m.kind === 'vel'))!;

    // The mode buttons come from the module and so render before the
    // parameters arrive; wait for the knob itself, not for the switch.
    await waitFor(() => expect(screen.getByRole('slider', { name: gain.label })).toBeDefined());
    fireEvent.click(screen.getByRole('button', { name: 'VEL' }));

    const knob = screen.getByRole('slider', { name: `${gain.label} vel depth` });
    // The depth's range, not the parameter's — a depth is bipolar.
    expect(knob.getAttribute('aria-valuemin')).toBe('-1');
    expect(knob.getAttribute('aria-valuemax')).toBe('1');
  });

  it('makes knobs with no depth for that mode inert rather than editable', async () => {
    renderYutani();
    const plain = yutaniModule.panels
      .flatMap((p) => p.controls)
      .find((c) => c.kind === 'knob' && !c.modifiers?.some((m) => m.kind === 'lfo'))!;

    await waitFor(() => expect(screen.getByRole('slider', { name: plain.label })).toBeDefined());
    fireEvent.click(screen.getByRole('button', { name: 'LINK' }));
    expect(screen.getByRole('slider', { name: plain.label }).getAttribute('aria-disabled'))
      .toBe('true');
  });
});

describe('GridView panel switches', () => {
  it('shows a section switch reflecting the parameter', async () => {
    renderYutani();
    const panel = yutaniModule.panels.find((p) => p.enable)!;
    await waitFor(() => expect(
      screen.getByRole('switch', { name: `${panel.label} on` }),
    ).toBeDefined());
    expect(
      screen.getByRole('switch', { name: `${panel.label} on` }).getAttribute('aria-checked'),
    ).toBe('true');
  });

  it('sends the section switch to its own parameter', async () => {
    const { setFxParam } = renderYutani();
    const panel = yutaniModule.panels.find((p) => p.enable)!;
    await waitFor(() => expect(
      screen.getByRole('switch', { name: `${panel.label} on` }),
    ).toBeDefined());

    fireEvent.click(screen.getByRole('switch', { name: `${panel.label} on` }));
    expect(setFxParam).toHaveBeenCalledWith(0, 0, panel.enable!.slider - 1, 0);
  });
});

// ── Fitting the screen ───────────────────────────────────────
//
// Yutani's own window is 1444x576 and lays its panels out one row deep. A
// landscape iPad is far taller in proportion, so a fixed row cap left most of
// the screen empty and made every device wider than it needed to be.

describe('panel layout', () => {
  it('takes more rows when there is more height', () => {
    expect(maxRowsFor(300)).toBeLessThan(maxRowsFor(700));
  });

  it('never asks for fewer than one row, however cramped', () => {
    expect(maxRowsFor(1)).toBe(1);
    expect(maxRowsFor(0)).toBeGreaterThan(0);
  });

  it('stops growing rows past what a knob column can use', () => {
    expect(maxRowsFor(100000)).toBe(6);
  });

  it('balances columns rather than stranding one', () => {
    // Seven controls in six rows is 4+3, not 6+1.
    expect(shapeFor(7, 6)).toEqual({ cols: 2, rows: 4 });
    expect(shapeFor(5, 6)).toEqual({ cols: 1, rows: 5 });
    expect(shapeFor(12, 4)).toEqual({ cols: 3, rows: 4 });
  });

  it('always leaves room for every control', () => {
    for (let count = 1; count <= 40; count++) {
      for (let rows = 1; rows <= 6; rows++) {
        const s = shapeFor(count, rows);
        expect(s.rows * s.cols).toBeGreaterThanOrEqual(count);
        expect(s.rows).toBeLessThanOrEqual(rows);
      }
    }
  });
});

// ── Section tabs ─────────────────────────────────────────────
//
// Yutani's 22 panels run several screens wide, and panning past all of them to
// reach the filter is worse than one tap. The split follows the plugin's own
// layout rows — it draws its sections in four, and those rows already mean
// sources, filter, envelopes, modulation.

describe('Yutani section tabs', () => {
  it('splits into the plugin’s four layout rows', () => {
    expect(yutaniModule.groups).toEqual(['Source', 'Filter', 'Envelopes', 'Mod & FX']);
  });

  it('assigns every panel to a group that exists', () => {
    for (const p of yutaniModule.panels) {
      expect(p.group).toBeGreaterThanOrEqual(0);
      expect(p.group).toBeLessThan(yutaniModule.groups!.length);
    }
  });

  it('leaves no group empty', () => {
    for (let i = 0; i < yutaniModule.groups!.length; i++) {
      expect(yutaniModule.panels.some((p) => p.group === i)).toBe(true);
    }
  });

  it('shows only the selected section, and switches on tap', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('tablist', { name: 'Sections' })).toBeDefined());

    const first = yutaniModule.panels.find((p) => p.group === 0)!;
    const later = yutaniModule.panels.find((p) => p.group === 2)!;

    expect(screen.getByText(first.label)).toBeDefined();
    expect(screen.queryByText(later.label)).toBeNull();

    fireEvent.click(screen.getByRole('tab', { name: 'Envelopes' }));
    expect(screen.getByText(later.label)).toBeDefined();
    expect(screen.queryByText(first.label)).toBeNull();
  });

  it('leaves an untabbed module showing everything at once', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByTestId('grid-device-title')).toBeDefined());
    // Info is always there; what a module without groups must not get is
    // section tabs that hide half of it.
    expect(screen.getAllByRole('tab').map((t) => t.textContent)).toEqual(['Info']);
    for (const label of ['Voices', 'Motion', 'Output']) {
      expect(screen.getByText(label)).toBeDefined();
    }
  });
});

describe('fit scale', () => {
  it('fills the height when a device is short of it', () => {
    expect(fitScaleFor(600, 500)).toBeCloseTo(1.2);
  });

  it('shrinks a device that overflows', () => {
    expect(fitScaleFor(600, 900)).toBeCloseTo(2 / 3);
  });

  it('refuses to blow a small device up without limit', () => {
    expect(fitScaleFor(900, 100)).toBeLessThanOrEqual(1.35);
  });

  it('refuses to shrink past legibility', () => {
    expect(fitScaleFor(100, 5000)).toBeGreaterThanOrEqual(0.5);
  });

  it('stays put before it has been measured', () => {
    expect(fitScaleFor(0, 500)).toBe(1);
    expect(fitScaleFor(600, 0)).toBe(1);
  });
});

// ── Info panel and presets ───────────────────────────────────

describe('device info', () => {
  it('is reachable on every device, tabbed or not', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByRole('tab', { name: 'Info' })).toBeDefined());
  });

  it('replaces the panels rather than sitting alongside them', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('tab', { name: 'Source' })).toBeDefined());
    const panel = yutaniModule.panels.find((p) => p.group === 0)!;

    expect(screen.getByText(panel.label)).toBeDefined();
    fireEvent.click(screen.getByRole('tab', { name: 'Info' }));
    expect(screen.queryByText(panel.label)).toBeNull();
    expect(screen.getByText('Modulation')).toBeDefined();
  });

  it('describes the modes this device actually has', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('tab', { name: 'Info' })).toBeDefined());
    fireEvent.click(screen.getByRole('tab', { name: 'Info' }));
    expect(screen.getByText(/velocity of a note moves the knob/)).toBeDefined();
  });

  it('says nothing about modulation on a device without any', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByRole('tab', { name: 'Info' })).toBeDefined());
    fireEvent.click(screen.getByRole('tab', { name: 'Info' }));
    expect(screen.queryByText('Modulation')).toBeNull();
  });

  it('hides the modulation switch while the info panel is up', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('button', { name: 'VEL' })).toBeDefined());
    fireEvent.click(screen.getByRole('tab', { name: 'Info' }));
    expect(screen.queryByRole('button', { name: 'VEL' })).toBeNull();
  });
});

describe('preset picker', () => {
  it('shows the preset the plugin reports', async () => {
    renderYutani();
    await waitFor(() => expect(screen.getByRole('group', { name: 'Preset' })).toBeDefined());
    expect(screen.getByRole('button', { name: 'Preset: Reese' })).toBeDefined();
  });

  it('steps to the neighbouring preset', async () => {
    const { setFxPreset } = renderYutani();
    await waitFor(() => expect(screen.getByRole('group', { name: 'Preset' })).toBeDefined());

    fireEvent.click(screen.getByRole('button', { name: 'Next preset' }));
    expect(setFxPreset).toHaveBeenCalledWith(0, 0, 2);
  });

  it('wraps around either end rather than stopping', async () => {
    const { setFxPreset } = renderYutani();
    await waitFor(() => expect(screen.getByRole('group', { name: 'Preset' })).toBeDefined());

    // Reported index is 1 of 4; two steps back lands on 3, not -1.
    fireEvent.click(screen.getByRole('button', { name: 'Previous preset' }));
    await waitFor(() => expect(setFxPreset).toHaveBeenCalledWith(0, 0, 0));
    fireEvent.click(screen.getByRole('button', { name: 'Previous preset' }));
    await waitFor(() => expect(setFxPreset).toHaveBeenCalledWith(0, 0, 3));
  });

  it('fetches the full list only when it is opened', async () => {
    const { getAllFxPresetNames } = renderYutani();
    await waitFor(() => expect(screen.getByRole('group', { name: 'Preset' })).toBeDefined());
    expect(getAllFxPresetNames).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole('button', { name: 'Preset: Reese' }));
    await waitFor(() => expect(screen.getByRole('option', { name: 'Hoover' })).toBeDefined());
    expect(getAllFxPresetNames).toHaveBeenCalledTimes(1);
  });

  it('re-reads every parameter after a preset lands', async () => {
    const { getFxParams, setFxPreset } = renderYutani();
    await waitFor(() => expect(screen.getByRole('group', { name: 'Preset' })).toBeDefined());
    const before = getFxParams.mock.calls.length;

    fireEvent.click(screen.getByRole('button', { name: 'Next preset' }));
    await waitFor(() => expect(setFxPreset).toHaveBeenCalled());
    // A preset rewrites everything at once and reports no per-parameter change.
    await waitFor(() => expect(getFxParams.mock.calls.length).toBeGreaterThan(before));
  });

  it('stays out of the way when the plugin has no presets', async () => {
    renderGrid([{ index: 0, name: 'JS: Chorus' }]);
    await waitFor(() => expect(screen.getByTestId('grid-device-title')).toBeDefined());
    expect(screen.queryByRole('group', { name: 'Preset' })).toBeNull();
  });
});

// ── MIDI ARP ─────────────────────────────────────────────────
//
// The arp declares all 40 of its sliders hidden, so REAPER shows none of them
// and neither does the plugin — everything is drawn from its @gfx. The module
// therefore mirrors the control bar the source draws, not the parameter list,
// which is mostly CC assignment plumbing kept behind a right-click menu.

describe('MIDI ARP module', () => {
  const controls = midiArpModule.panels.flatMap((p) => p.controls);

  it('leads with the pattern grid, which is what the plugin is for', () => {
    const first = midiArpModule.panels.filter((p) => p.group === 0)
      .flatMap((p) => p.controls);
    expect(first.some((c) => c.kind === 'notegrid')).toBe(true);
  });

  it('carries the controls the plugin puts on its own bar', () => {
    const arp = midiArpModule.panels.filter((p) => p.group === 1)
      .flatMap((p) => p.controls).map((c) => c.label);
    // Pattern selection moved next to the grid it selects; the rest of the
    // plugin's bar lives here.
    for (const label of ['Follow', 'Length', 'Speed', 'Swing',
      'Voices', 'Octaves', 'Repeat', 'Sort notes']) {
      expect(arp).toContain(label);
    }
  });

  it('keeps CC assignment off the performance tab', () => {
    const arp = midiArpModule.panels.filter((p) => p.group <= 1);
    expect(arp.some((p) => p.label.startsWith('CC '))).toBe(false);
    // Still reachable, just not in the way.
    expect(midiArpModule.panels.filter((p) => p.label.startsWith('CC ')).length).toBe(8);
  });

  it('offers the three repeat modes the GUI draws, not the six declared', () => {
    const mode = controls.find((c) => c.label === 'Repeat')!;
    expect(mode.kind).toBe('segmented');
    expect((mode as { options: { label: string }[] }).options.map((o) => o.label))
      .toEqual(['Once', 'Rep', 'Bidi']);
  });

  it('can reach Free, which the plugin numbers 2 rather than 1', () => {
    const clock = controls.find((c) => c.label === 'Clock')!;
    const options = (clock as { options: { value: number; label: string }[] }).options;
    expect(options.find((o) => o.label === 'Free')!.value).toBe(2);
    expect(options.find((o) => o.label === 'MIDI')!.value).toBe(1);
  });

  it('names every control against a parameter', () => {
    // Except the note grid, which spans a block of them rather than one.
    const single = controls.filter((c) => c.kind !== 'notegrid');
    expect(single.every((c) => c.expect && c.expect.length > 0)).toBe(true);
  });

  it('never drives the same parameter from two controls', () => {
    const sliders = controls.map((c) => c.slider);
    expect(sliders.length).toBe(new Set(sliders).size);
  });
});

// ── Note grid ────────────────────────────────────────────────
//
// The plugin stores a note as a run: a positive cell where it starts, then
// negatives holding it. Getting that encoding wrong produces patterns its own
// editor cannot make — a tail with no head, or a row of repeats where one long
// note was meant.

describe('note grid', () => {
  const ROWS = 5;
  const COLS = 32;
  const FIRST = 60;

  /** Parameters for the window, plus the two that position it. */
  function gridParams(cells: Record<string, number> = {}): FxParam[] {
    const out: FxParam[] = [
      { index: 57, name: 'Grid row offset', value: 0, min: 0, max: 55, mid: 27 },
      { index: 58, name: 'Grid column page', value: 0, min: 0, max: 1, mid: 0 },
    ];
    for (let r = 0; r < ROWS; r++) {
      for (let c = 0; c < COLS; c++) {
        out.push({
          index: FIRST - 1 + r * COLS + c,
          name: `Step ${r},${c}`,
          value: cells[`${r},${c}`] ?? 0,
          min: -16, max: 16, mid: 0,
        });
      }
    }
    return out;
  }

  const control = midiArpModule.panels
    .flatMap((p) => p.controls)
    .find((c) => c.kind === 'notegrid')!;

  function renderNoteGrid(cells?: Record<string, number>) {
    const onChange = vi.fn();
    render(
      <NoteGrid
        control={control as never}
        params={gridParams(cells)}
        onChange={onChange}
      />,
    );
    return onChange;
  }

  it('draws a cell for every step in the window', () => {
    renderNoteGrid();
    // By name, so the shape buttons above the grid aren't counted as cells.
    expect(screen.getAllByRole('button', { name: /^Row \d+ step \d+$/ }))
      .toHaveLength(ROWS * COLS);
  });

  it('labels rows by their position in the pattern', () => {
    renderNoteGrid();
    expect(screen.getByLabelText('Row 0 step 1')).toBeDefined();
    expect(screen.getByLabelText('Row 4 step 32')).toBeDefined();
  });

  it('starts a note on an empty cell', () => {
    const onChange = renderNoteGrid();
    const cell = screen.getByLabelText('Row 2 step 5');
    fireEvent.pointerDown(cell, { pointerId: 1 });
    fireEvent.pointerUp(window, { pointerId: 1 });
    // Row 2, step 5 is index FIRST-1 + 2*COLS + 4.
    expect(onChange).toHaveBeenCalledWith(FIRST - 1 + 2 * COLS + 4, 1);
  });

  it('clears the whole note when its head is tapped, not just one cell', () => {
    // A three-step note: head at step 3, held through 5.
    const onChange = renderNoteGrid({ '0,2': 1, '0,3': -1, '0,4': -1 });
    fireEvent.pointerDown(screen.getByLabelText('Row 0 step 3'), { pointerId: 1 });
    fireEvent.pointerUp(window, { pointerId: 1 });

    const cleared = onChange.mock.calls.filter((c) => c[1] === 0).map((c) => c[0]);
    expect(cleared).toEqual([FIRST - 1 + 2, FIRST - 1 + 3, FIRST - 1 + 4]);
  });

  it('clears the whole note when a held cell is tapped', () => {
    const onChange = renderNoteGrid({ '0,2': 1, '0,3': -1, '0,4': -1 });
    fireEvent.pointerDown(screen.getByLabelText('Row 0 step 4'), { pointerId: 1 });
    fireEvent.pointerUp(window, { pointerId: 1 });

    const cleared = onChange.mock.calls.filter((c) => c[1] === 0).map((c) => c[0]);
    // Walks back to the head rather than leaving a tail with nothing to hold.
    expect(cleared).toContain(FIRST - 1 + 2);
  });

  it('marks a filled cell as pressed for assistive tech', () => {
    renderNoteGrid({ '1,0': 1 });
    expect(screen.getByLabelText('Row 1 step 1').getAttribute('aria-pressed')).toBe('true');
    expect(screen.getByLabelText('Row 1 step 2').getAttribute('aria-pressed')).toBe('false');
  });
});

describe('following changes made outside the Grid', () => {
  it('updates a control when the plugin reports a parameter moved', async () => {
    const params = yutaniParams();
    let fire: ((msg: unknown) => void) | null = null;
    const onEvent = vi.fn((event: string, handler: (msg: unknown) => void) => {
      if (event === 'event:fx_param_changed') fire = handler;
      return () => {};
    });

    render(
      <GridView
        tracks={tracks}
        selectedTrack={0}
        getTrackFx={vi.fn().mockResolvedValue([{ index: 0, name: 'JS: Yutani [Spidercrab]' }])}
        getFxParams={vi.fn().mockResolvedValue({
          params, total: params.length, offset: 0, limit: 256,
        })}
        setFxParam={vi.fn().mockResolvedValue({ payload: {} })}
        onEvent={onEvent}
      />,
    );

    const gain = yutaniModule.panels.flatMap((p) => p.controls)
      .find((c) => c.kind === 'knob')!;
    await waitFor(() =>
      expect(screen.getByRole('slider', { name: gain.label })).toBeDefined());
    expect(fire).not.toBeNull();

    // The plugin's own window moved it; without this path the Grid would go on
    // showing the value it last fetched.
    fire!({
      payload: {
        trackIdx: 0,
        fxIdx: 0,
        params: [{ index: gain.slider - 1, value: 0.75, formatted: '0.75' }],
      },
    });

    await waitFor(() => expect(
      screen.getByRole('slider', { name: gain.label }).getAttribute('aria-valuenow'),
    ).toBe('0.75'));
  });

  it('ignores changes reported for a different plugin', async () => {
    const params = yutaniParams();
    let fire: ((msg: unknown) => void) | null = null;
    render(
      <GridView
        tracks={tracks}
        selectedTrack={0}
        getTrackFx={vi.fn().mockResolvedValue([{ index: 0, name: 'JS: Yutani [Spidercrab]' }])}
        getFxParams={vi.fn().mockResolvedValue({
          params, total: params.length, offset: 0, limit: 256,
        })}
        setFxParam={vi.fn().mockResolvedValue({ payload: {} })}
        onEvent={(event, handler) => {
          if (event === 'event:fx_param_changed') fire = handler;
          return () => {};
        }}
      />,
    );

    const gain = yutaniModule.panels.flatMap((p) => p.controls)
      .find((c) => c.kind === 'knob')!;
    await waitFor(() =>
      expect(screen.getByRole('slider', { name: gain.label })).toBeDefined());
    const before = screen.getByRole('slider', { name: gain.label }).getAttribute('aria-valuenow');

    fire!({ payload: { trackIdx: 0, fxIdx: 7, params: [{ index: gain.slider - 1, value: 0.9 }] } });
    expect(screen.getByRole('slider', { name: gain.label }).getAttribute('aria-valuenow'))
      .toBe(before);
  });
});

// ── Help on a long press ─────────────────────────────────────
//
// An arp is full of terms that mean nothing until someone says what they are —
// CC, poly mode, swing. The label alone leaves the reader guessing, and there
// is no room on screen to explain everything at once.

describe('control help', () => {
  function hold(el: Element) {
    fireEvent.pointerDown(el, { clientX: 10, clientY: 10 });
    act(() => { vi.advanceTimersByTime(600); });
  }

  beforeEach(() => vi.useFakeTimers());
  afterEach(() => vi.useRealTimers());

  it('says nothing until the label is held', () => {
    render(<HelpLabel text="Swing" help="Delays every other step." />);
    expect(screen.queryByRole('tooltip')).toBeNull();
    hold(screen.getByText('Swing'));
    expect(screen.getByRole('tooltip').textContent).toContain('Delays every other step.');
  });

  it('treats a short press as a press, not a question', () => {
    render(<HelpLabel text="Swing" help="Delays every other step." />);
    fireEvent.pointerDown(screen.getByText('Swing'), { clientX: 10, clientY: 10 });
    act(() => { vi.advanceTimersByTime(200); });
    fireEvent.pointerUp(screen.getByText('Swing'));
    act(() => { vi.advanceTimersByTime(600); });
    expect(screen.queryByRole('tooltip')).toBeNull();
  });

  it('abandons the hold if the finger travels — that is a drag', () => {
    render(<HelpLabel text="Swing" help="Delays every other step." />);
    const label = screen.getByText('Swing');
    fireEvent.pointerDown(label, { clientX: 10, clientY: 10 });
    fireEvent.pointerMove(label, { clientX: 60, clientY: 10 });
    act(() => { vi.advanceTimersByTime(600); });
    expect(screen.queryByRole('tooltip')).toBeNull();
  });

  it('stays a plain label when there is nothing to explain', () => {
    render(<HelpLabel text="Swing" />);
    hold(screen.getByText('Swing'));
    expect(screen.queryByRole('tooltip')).toBeNull();
  });
});

describe('MIDI ARP help text', () => {
  const controls = midiArpModule.panels.flatMap((p) => p.controls);

  it('explains every control', () => {
    const bare = controls.filter((c) => !c.help).map((c) => c.label);
    expect(bare).toEqual([]);
  });

  it('says what a CC is wherever one is mentioned', () => {
    const ccControls = controls.filter((c) => /^CC/.test(c.label));
    expect(ccControls.length).toBeGreaterThan(0);
    // Naming the acronym is the whole point; "sends CC 3" teaches nobody.
    expect(ccControls.every((c) => c.help!.includes('Continuous Controller'))).toBe(true);
  });

  it('puts the lane switches beside the grid they add rows to', () => {
    const lanes = midiArpModule.panels.find((p) => p.label === 'Lanes')!;
    expect(lanes.group).toBe(0);
    const grid = midiArpModule.panels.find(
      (p) => p.controls.some((c) => c.kind === 'notegrid'))!;
    expect(grid.group).toBe(0);
  });
});

// ── Arpeggiator shapes ───────────────────────────────────────
//
// Saike's arp has no style menu — an arpeggio here is drawn, and "up" is a
// diagonal. These write the diagonal and leave it editable, which is what a
// Style menu gives you without taking the grid away afterwards.

describe('pattern shapes', () => {
  const ROWS = 5;
  const COLS = 32;
  const FIRST = 60;

  function gridParams(): FxParam[] {
    const out: FxParam[] = [
      { index: 57, name: 'Grid row offset', value: 0, min: 0, max: 55, mid: 27 },
      { index: 58, name: 'Grid column page', value: 0, min: 0, max: 1, mid: 0 },
    ];
    for (let r = 0; r < ROWS; r++) {
      for (let c = 0; c < COLS; c++) {
        out.push({
          index: FIRST - 1 + r * COLS + c, name: `Step ${r},${c}`,
          value: 0, min: -16, max: 16, mid: 0,
        });
      }
    }
    return out;
  }

  const control = midiArpModule.panels.flatMap((p) => p.controls)
    .find((c) => c.kind === 'notegrid')!;

  /** Which row each step ends up on, from the writes the shape made. */
  function rowsWritten(onChange: ReturnType<typeof vi.fn>) {
    const placed = new Map<number, number>();
    for (const [index, value] of onChange.mock.calls) {
      if (value !== 1) continue;
      const off = index - (FIRST - 1);
      placed.set(off % COLS, Math.floor(off / COLS));
    }
    return placed;
  }

  function apply(name: string) {
    const onChange = vi.fn();
    render(<NoteGrid control={control as never} params={gridParams()} onChange={onChange} />);
    fireEvent.click(screen.getByRole('button', { name }));
    return onChange;
  }

  it('writes an ascending diagonal for Up', () => {
    const placed = rowsWritten(apply('Up'));
    expect([0, 1, 2, 3, 4, 5, 6].map((c) => placed.get(c)))
      .toEqual([0, 1, 2, 3, 4, 0, 1]);
  });

  it('writes a descending diagonal for Down', () => {
    const placed = rowsWritten(apply('Down'));
    expect([0, 1, 2, 3, 4, 5].map((c) => placed.get(c)))
      .toEqual([4, 3, 2, 1, 0, 4]);
  });

  it('turns around without repeating the end notes for Up/Down', () => {
    const placed = rowsWritten(apply('Up/Down'));
    // Period is 2*rows-2, so 4 is played once at the top, not twice.
    expect([0, 1, 2, 3, 4, 5, 6, 7, 8].map((c) => placed.get(c)))
      .toEqual([0, 1, 2, 3, 4, 3, 2, 1, 0]);
  });

  it('puts exactly one note in each step', () => {
    const onChange = apply('Up');
    const ones = onChange.mock.calls.filter(([, v]) => v === 1);
    expect(ones).toHaveLength(COLS);
  });

  it('leaves nothing behind for Clear', () => {
    const onChange = apply('Clear');
    expect(onChange.mock.calls.every(([, v]) => v === 0)).toBe(true);
  });
});
