// Generated by tools/jsfx_module_gen.py, then hand-tuned with step grids.
// 226 parameters, 19 panels + 17 step grid rows.
//
// Regenerate with: tools/jsfx_module_gen.py <path> --title SEQS
// Then re-apply the step grid rows and HAND corrections.
import type { ModuleDef } from './modules';

// 17 effect rows, with step window slider indices (8 per row, starting at 115)
const STEP_BASE = 115;
const ROWS = [
  ['Reset',     1,  0],
  ['Slowdown',  2,  1],
  ['Tape Stop', 10, 2],
  ['Retrigger', 4,  3],
  ['Reverse',   5,  4],
  ['Pitch',     12, 5],
  ['Degrade',   9,  6],
  ['Filter',    7,  7],
  ['Gate',      6,  8],
  ['Reverb',    8,  9],
  ['Karplus',   11, 10],
  ['Mod FX',    20, 11],
  ['Filter 2',  21, 12],
  ['Delay',     22, 13],
  ['Chorus',    23, 14],
  ['Freq Shift',26, 15],
  ['Mod A',     50, 16],
] as const;

const ROW_SEL = 251;

export const seqsModule: ModuleDef = {
  title: 'SEQS',
  match: (n) => n.toLowerCase().includes('seqs'),
  groups: ['Transport', 'Grid', 'Effects', 'Modulation'],
  panels: [
    // ── Transport ──────────────────────────────────────────
    {
      label: 'Transport',
      group: 0,
      controls: [
        { kind: 'knob', slider: 1, expect: 'Current speed', label: 'Speed', format: (v) => `${v.toFixed(0)}` },
        { kind: 'knob', slider: 2, expect: 'Current pattern', label: 'Pattern', format: (v) => `${Math.round(v)}` },
        { kind: 'knob', slider: 6, expect: 'Shuffle amount', label: 'Shuffle', format: (v) => `${v.toFixed(0)}%` },
        { kind: 'knob', slider: 64, expect: 'First Pattern', label: 'MIDI note', format: (v) => `${Math.round(v)}` },
      ],
    },
    {
      label: 'Transport',
      group: 0,
      controls: [
        { kind: 'toggle', slider: 7, expect: 'Playback enabled', label: 'Play' },
        { kind: 'toggle', slider: 8, expect: 'Record enabled', label: 'Rec' },
        { kind: 'toggle', slider: 10, expect: 'Reset enabled', label: 'Reset' },
      ],
    },

    // ── Grid (step grid) ───────────────────────────────────
    ...ROWS.map(([label, mem, ri]) => {
      const sliders: [number, number, number, number, number, number, number, number] =
        [STEP_BASE + ri * 8, STEP_BASE + ri * 8 + 1, STEP_BASE + ri * 8 + 2, STEP_BASE + ri * 8 + 3,
         STEP_BASE + ri * 8 + 4, STEP_BASE + ri * 8 + 5, STEP_BASE + ri * 8 + 6, STEP_BASE + ri * 8 + 7];
      return {
        label,
        group: 1,
        controls: [
          {
            kind: 'stepgrid' as const,
            slider: sliders[0],
            expect: undefined,
            label,
            steps: 32,
            maxValue: 31,
            stepSliders: sliders,
            rowSelector: ROW_SEL,
          },
        ],
      };
    }),
    // Row selector (hidden, controls which row's data is in the step sliders)
    {
      label: 'Row',
      group: 1,
      controls: [
        { kind: 'knob', slider: ROW_SEL, expect: 'Edit row', label: 'Edit row', format: (v) => `${ROWS[Math.round(v)]?.[0] ?? v.toFixed(0)}` },
      ],
    },

    // ── Effects (auto-generated panels) ────────────────────
    {
      label: 'SAMPLE',
      group: 2,
      controls: [
        { kind: 'knob', slider: 69, expect: 'Selected Details', label: 'Sample' },
        { kind: 'toggle', slider: 9, expect: 'Chorus enabled', label: 'Store' },
      ],
    },
    {
      label: 'MASTER',
      group: 2,
      controls: [
        { kind: 'toggle', slider: 113, expect: 'Hide Pdc', label: 'PDC' },
      ],
    },
    {
      label: 'Slowdown',
      group: 2,
      enable: { slider: 11, expect: 'Slowdown enabled' },
      controls: [
        { kind: 'toggle', slider: 108, expect: 'Slowdown Scaling', label: 'Scaling' },
      ],
    },
    {
      label: 'Filter 2',
      group: 2,
      enable: { slider: 23, expect: 'Filter enabled' },
      controls: [
        { kind: 'knob', slider: 26, expect: 'Filter Drive (dB)', label: 'Drive' },
        { kind: 'knob', slider: 29, expect: 'Resonance', label: 'Resonance' },
        { kind: 'segmented', slider: 101, expect: 'Filter2 Type', label: 'Type', options: [
          { value: 0, label: 'Lin2p' }, { value: 1, label: 'MS20' }, { value: 2, label: 'Lin4p' },
          { value: 3, label: 'Moog' }, { value: 4, label: 'Ladder' }, { value: 5, label: '303' },
          { value: 6, label: 'MS20A' }, { value: 8, label: 'Dual' }, { value: 9, label: 'Triple' },
          { value: 10, label: 'SVF2p' }, { value: 11, label: 'SVF4p' }, { value: 14, label: 'Rect' },
          { value: 15, label: 'Steiner' }, { value: 16, label: 'SteinerA' }, { value: 17, label: 'Bent' },
          { value: 18, label: 'Pill2p' }, { value: 19, label: 'Pill4p' }, { value: 22, label: 'Pill2p S' },
          { value: 23, label: 'Pill4p S' }, { value: 27, label: 'Vowel' },
        ]},
        { kind: 'knob', slider: 63, expect: 'Filter Inertia [ms]', label: 'Inertia' },
      ],
    },
    {
      label: 'Filter',
      group: 2,
      enable: { slider: 16, expect: 'Filter enabled' },
      controls: [
        { kind: 'knob', slider: 26, expect: 'Filter Drive (dB)', label: 'Drive' },
        { kind: 'knob', slider: 29, expect: 'Resonance', label: 'Resonance' },
        { kind: 'segmented', slider: 25, expect: 'Filter type', label: 'Type', options: [
          { value: 0, label: 'Linear' }, { value: 1, label: 'MS-20' }, { value: 2, label: 'Linear x2' },
          { value: 3, label: 'Moog' }, { value: 4, label: 'Ladder' }, { value: 5, label: '303' },
          { value: 6, label: 'MS-20 asym' }, { value: 7, label: 'DblRes' }, { value: 8, label: 'DualPeak' },
          { value: 9, label: 'TriplePeak' }, { value: 10, label: 'svf nl 2p' }, { value: 11, label: 'svf nl 4p' },
          { value: 12, label: 'svf nl 2p inc' }, { value: 13, label: 'svf nl 4p inc' },
          { value: 14, label: 'rectified resonance' }, { value: 15, label: 'Steiner' },
          { value: 16, label: 'SteinerA' }, { value: 17, label: 'Muck' }, { value: 18, label: 'Pill2p' },
          { value: 19, label: 'Pill4p' }, { value: 20, label: 'Pill2p Aggro' }, { value: 21, label: 'Pill4p Aggro' },
          { value: 22, label: 'Pill2p Stacc' }, { value: 23, label: 'Pill4p Stacc' },
          { value: 24, label: 'Ladder3' }, { value: 25, label: 'Ladder6' }, { value: 26, label: 'HLadder' },
        ]},
        { kind: 'knob', slider: 27, expect: 'Cutoff Start', label: 'Cut S' },
        { kind: 'knob', slider: 28, expect: 'Cutoff Finish', label: 'Cut E' },
        { kind: 'knob', slider: 30, expect: 'Morph', label: 'Morph' },
        { kind: 'knob', slider: 63, expect: 'Filter Inertia [ms]', label: 'Inertia' },
      ],
    },
    {
      label: 'Gate',
      group: 2,
      enable: { slider: 15, expect: 'Gate enabled' },
      controls: [
        { kind: 'knob', slider: 72, expect: 'Gate Attack', label: 'Atk' },
        { kind: 'knob', slider: 73, expect: 'Gate Decay', label: 'Dec' },
        { kind: 'knob', slider: 74, expect: 'Gate Sustain', label: 'Sus' },
        { kind: 'knob', slider: 70, expect: 'Gate Start', label: 'Start' },
        { kind: 'knob', slider: 71, expect: 'Gate Stop', label: 'Stop' },
      ],
    },
    {
      label: 'Reverb',
      group: 2,
      enable: { slider: 17, expect: 'Reverb enabled' },
      controls: [
        { kind: 'knob', slider: 76, expect: 'Verb Diffusion', label: 'Diff' },
        { kind: 'knob', slider: 77, expect: 'Verb Decay', label: 'Decay' },
        { kind: 'knob', slider: 78, expect: 'Verb Mod Depth', label: 'Mod D' },
        { kind: 'knob', slider: 79, expect: 'Verb Mod Rate', label: 'Mod R' },
        { kind: 'knob', slider: 80, expect: 'Verb Lowpass', label: 'Damp' },
        { kind: 'knob', slider: 81, expect: 'Verb Highpass', label: 'HP' },
        { kind: 'knob', slider: 82, expect: 'Verb Dry', label: 'Dry' },
        { kind: 'knob', slider: 83, expect: 'Verb Wet', label: 'Wet' },
      ],
    },
    {
      label: 'Degrade',
      group: 2,
      enable: { slider: 18, expect: 'Degrade enabled' },
      controls: [
        { kind: 'knob', slider: 84, expect: 'Bitrate', label: 'Bits' },
        { kind: 'knob', slider: 85, expect: 'Samplerate', label: 'Smp' },
        { kind: 'knob', slider: 86, expect: 'Saturation', label: 'Sat' },
      ],
    },
    {
      label: 'Tape Stop',
      group: 2,
      enable: { slider: 19, expect: 'Tapestop enabled' },
      controls: [
        { kind: 'knob', slider: 87, expect: 'Tapestop Decay', label: 'Time' },
        { kind: 'knob', slider: 88, expect: 'Tapestop Shape', label: 'Shape' },
        { kind: 'knob', slider: 89, expect: 'Tapestop Depth', label: 'Depth' },
      ],
    },
    {
      label: 'Karplus',
      group: 2,
      enable: { slider: 20, expect: 'Karplus enabled' },
      controls: [
        { kind: 'knob', slider: 90, expect: 'Karplus Pitch', label: 'Pitch' },
        { kind: 'knob', slider: 91, expect: 'Karplus Cutoff', label: 'Damp' },
        { kind: 'knob', slider: 92, expect: 'Karplus Feedback', label: 'Feed' },
        { kind: 'knob', slider: 93, expect: 'Karplus Wet', label: 'Wet' },
        { kind: 'knob', slider: 94, expect: 'Karplus Dry', label: 'Dry' },
      ],
    },
    {
      label: 'Pitch',
      group: 2,
      enable: { slider: 21, expect: 'Pitch shifter enabled' },
      controls: [
        { kind: 'knob', slider: 34, expect: 'Pitch Shift', label: 'Pitch' },
        { kind: 'knob', slider: 95, expect: 'Shifter Dry', label: 'Dry' },
        { kind: 'knob', slider: 96, expect: 'Shifter Wet', label: 'Wet' },
      ],
    },
    {
      label: 'Delay',
      group: 2,
      enable: { slider: 24, expect: 'Delay enabled' },
      controls: [
        { kind: 'knob', slider: 97, expect: 'Delay Time', label: 'Time' },
        { kind: 'knob', slider: 98, expect: 'Delay Feedback', label: 'Feed' },
        { kind: 'toggle', slider: 104, expect: 'Delay Gain Mode', label: 'Gain' },
      ],
    },
    {
      label: 'Chorus',
      group: 2,
      enable: { slider: 9, expect: 'Chorus enabled' },
      controls: [
        { kind: 'knob', slider: 105, expect: 'Chorus Depth', label: 'Depth' },
        { kind: 'knob', slider: 106, expect: 'Chorus Speed', label: 'Speed' },
      ],
    },

    // ── Modulation ─────────────────────────────────────────
    {
      label: 'Modulator A',
      group: 3,
      controls: [
        { kind: 'knob', slider: 109, expect: 'Modulator Wet', label: 'Wet' },
        { kind: 'knob', slider: 110, expect: 'Modulator Pitch', label: 'Pitch' },
        { kind: 'knob', slider: 111, expect: 'Modulator Offset', label: 'RM/AM' },
        { kind: 'knob', slider: 112, expect: 'Modulator Phase', label: 'Phase' },
      ],
    },
    {
      label: 'Modulator B',
      group: 3,
      controls: [
        { kind: 'knob', slider: 109, expect: 'Modulator Wet', label: 'Wet' },
        { kind: 'knob', slider: 110, expect: 'Modulator Pitch', label: 'Pitch' },
        { kind: 'knob', slider: 111, expect: 'Modulator Offset', label: 'RM/AM' },
        { kind: 'knob', slider: 112, expect: 'Modulator Phase', label: 'Phase' },
      ],
    },
  ],
};