// Generated by tools/jsfx_module_gen.py from /mnt/c/Users/Tamura/AppData/Roaming/REAPER/Effects/Saike Tools/SequencedFX/SequencedFX_spidercrab.jsfx
// 226 parameters, 19 panels, 156 unattributed.
//
// Regenerate rather than hand-editing wholesale, but the few
// corrections below the generator can't make are marked HAND.
import type { ModuleDef } from './modules';

export const seqsModule: ModuleDef = {
  title: 'SEQS',
  match: (n) => n.toLowerCase().includes('seqs'),
  panels: [
    {
      label: 'SAMPLE',
      enable: { slider: 9, expect: 'Chorus enabled' },
      controls: [
        { kind: 'knob', slider: 69, expect: 'Selected Details', label: 'Selected Details' },
      ],
    },
    {
      label: 'MASTER',
      controls: [
        { kind: 'toggle', slider: 113, expect: 'Hide Pdc', label: 'Hide Pdc' },
      ],
    },
    {
      label: 'SLOWDOWN',
      enable: { slider: 11, expect: 'Slowdown enabled' },
      controls: [
        { kind: 'toggle', slider: 108, expect: 'Slowdown Scaling', label: 'Slowdown Scaling' },
      ],
    },
    {
      label: 'RETRIGGER',
      enable: { slider: 13, expect: 'Retrigger enabled' },
      controls: [
      ],
    },
    {
      label: 'REVERSE',
      enable: { slider: 14, expect: 'Reverse enabled' },
      controls: [
      ],
    },
    {
      label: 'FILTER 2',
      enable: { slider: 23, expect: 'Filter enabled' },
      controls: [
        { kind: 'knob', slider: 26, expect: 'Filter Drive (dB)', label: 'Filter Drive (dB)' },
        { kind: 'knob', slider: 29, expect: 'Resonance', label: 'Resonance' },
        { kind: 'knob', slider: 101, expect: 'Filter2 Type', label: 'Filter2 Type' },
        { kind: 'toggle', slider: 102, expect: 'Filter Turn filter on and off', label: 'Filter Turn filter on and off' },
        { kind: 'toggle', slider: 114, expect: 'Legacy Mode', label: 'Legacy Mode' },
      ],
    },
    {
      label: 'FILTER',
      enable: { slider: 16, expect: 'Filter enabled' },
      controls: [
        { kind: 'segmented', slider: 25, expect: 'Filter type', label: 'Filter type', options: [{ value: 0, label: 'Linear' }, { value: 1, label: 'MS-20' }, { value: 2, label: 'Linear x2' }, { value: 3, label: 'Moog' }, { value: 4, label: 'Ladder' }, { value: 5, label: '303' }, { value: 6, label: 'MS-20 asym' }, { value: 7, label: 'DblRes' }, { value: 8, label: 'DualPeak' }, { value: 9, label: 'TriplePeak' }, { value: 10, label: 'svf nl 2p' }, { value: 11, label: 'svf nl 4p' }, { value: 12, label: 'svf nl 2p inc' }, { value: 13, label: 'svf nl 4p inc' }, { value: 14, label: 'rectified resonance' }, { value: 15, label: 'Steiner' }, { value: 16, label: 'SteinerA' }, { value: 17, label: 'Muck' }, { value: 18, label: 'Pill2p' }, { value: 19, label: 'Pill4p' }, { value: 20, label: 'Pill2p Aggro' }, { value: 21, label: 'Pill4p Aggro' }, { value: 22, label: 'Pill2p Stacc' }, { value: 23, label: 'Pill4p Stacc' }, { value: 24, label: 'Ladder3' }, { value: 25, label: 'Ladder6' }, { value: 26, label: 'HLadder' }] },
        { kind: 'toggle', slider: 100, expect: 'Turn filter on and off', label: 'Turn filter on and off' },
      ],
    },
    {
      label: 'VOLUME ENVELOPE',
      enable: { slider: 15, expect: 'Gate enabled' },
      controls: [
      ],
    },
    {
      label: 'REVERB',
      enable: { slider: 17, expect: 'Reverb enabled' },
      controls: [
      ],
    },
    {
      label: 'ENVELOPE',
      controls: [
        { kind: 'toggle', slider: 99, expect: 'Apply gate post-reverb', label: 'Apply gate post-reverb' },
      ],
    },
    {
      label: 'DEGRADE',
      enable: { slider: 18, expect: 'Degrade enabled' },
      controls: [
        { kind: 'knob', slider: 65, expect: 'Value', label: 'Value' },
      ],
    },
    {
      label: 'TAPE STOP',
      enable: { slider: 19, expect: 'Tapestop enabled' },
      controls: [
        { kind: 'toggle', slider: 112, expect: 'Set shape on the timeline', label: 'Set shape on the timeline' },
      ],
    },
    {
      label: 'PITCHED DELAY',
      enable: { slider: 20, expect: 'Karplus enabled' },
      controls: [
        { kind: 'toggle', slider: 94, expect: 'Snap Karplus', label: 'Snap Karplus' },
      ],
    },
    {
      label: 'PITCH SHIFTER',
      enable: { slider: 21, expect: 'Pitch shifter enabled' },
      controls: [
        { kind: 'toggle', slider: 95, expect: 'Snap Shifter', label: 'Snap Shifter' },
        { kind: 'knob', slider: 98, expect: 'Shifter Mode', label: 'Shifter Mode' },
      ],
    },
    {
      label: 'FREQ SHIFTER',
      enable: { slider: 36, expect: 'Frequency Shifter Enabled' },
      controls: [
      ],
    },
    {
      label: 'MOD FX',
      enable: { slider: 22, expect: 'Modulation enabled' },
      controls: [
        { kind: 'knob', slider: 37, expect: 'Sample playback offset', label: 'Sample playback offset' },
        { kind: 'toggle', slider: 103, expect: 'Snap Modulator', label: 'Snap Modulator' },
        { kind: 'knob', slider: 251, expect: 'Edit row', label: 'Edit row' },
      ],
    },
    {
      label: 'ENVELOPE',
      controls: [
        { kind: 'toggle', slider: 105, expect: 'Modulation Reset Phase', label: 'Modulation Reset Phase' },
      ],
    },
    {
      label: 'DELAY',
      enable: { slider: 24, expect: 'Delay enabled' },
      controls: [
        { kind: 'toggle', slider: 104, expect: 'Delay Gain Mode', label: 'Delay Gain Mode' },
      ],
    },
    {
      label: 'CHORUS',
      controls: [
        { kind: 'knob', slider: 66, expect: 'Count', label: 'Count' },
        { kind: 'knob', slider: 67, expect: 'Validate', label: 'Validate' },
        { kind: 'knob', slider: 68, expect: 'Sample Duration', label: 'Sample Duration' },
        { kind: 'knob', slider: 70, expect: 'Gate Start', label: 'Gate Start' },
        { kind: 'knob', slider: 71, expect: 'Gate Stop', label: 'Gate Stop' },
        { kind: 'knob', slider: 72, expect: 'Gate Attack', label: 'Gate Attack' },
        { kind: 'knob', slider: 73, expect: 'Gate Decay', label: 'Gate Decay' },
        { kind: 'knob', slider: 74, expect: 'Gate Sustain', label: 'Gate Sustain' },
        { kind: 'knob', slider: 75, expect: 'Verb Diffusion', label: 'Verb Diffusion' },
        { kind: 'knob', slider: 76, expect: 'Verb Decay', label: 'Verb Decay' },
        { kind: 'knob', slider: 77, expect: 'Verb Mod Depth', label: 'Verb Mod Depth' },
        { kind: 'knob', slider: 78, expect: 'Verb Mod Rate', label: 'Verb Mod Rate' },
        { kind: 'knob', slider: 79, expect: 'Verb Lowpass', label: 'Verb Lowpass' },
        { kind: 'knob', slider: 80, expect: 'Verb Highpass', label: 'Verb Highpass' },
        { kind: 'knob', slider: 81, expect: 'Verb Dry', label: 'Verb Dry' },
        { kind: 'knob', slider: 82, expect: 'Verb Wet', label: 'Verb Wet' },
        { kind: 'knob', slider: 83, expect: 'Verb Gate Attack', label: 'Verb Gate Attack' },
        { kind: 'knob', slider: 84, expect: 'Verb Gate Decay', label: 'Verb Gate Decay' },
        { kind: 'knob', slider: 85, expect: 'Verb Gate Sustain', label: 'Verb Gate Sustain' },
        { kind: 'knob', slider: 86, expect: 'Time Mode', label: 'Time Mode' },
        { kind: 'knob', slider: 87, expect: 'Tapestop Decay', label: 'Tapestop Decay' },
        { kind: 'toggle', slider: 88, expect: 'Tempo Sync Envelopes', label: 'Tempo Sync Envelopes' },
        { kind: 'knob', slider: 89, expect: 'Karplus Feedback', label: 'Karplus Feedback' },
        { kind: 'knob', slider: 90, expect: 'Karplus Cutoff', label: 'Karplus Cutoff' },
        { kind: 'knob', slider: 91, expect: 'Karplus Pitch', label: 'Karplus Pitch' },
        { kind: 'knob', slider: 92, expect: 'Karplus Wet', label: 'Karplus Wet' },
        { kind: 'knob', slider: 93, expect: 'Karplus Dry', label: 'Karplus Dry' },
        { kind: 'knob', slider: 96, expect: 'Shifter Dry', label: 'Shifter Dry' },
        { kind: 'knob', slider: 97, expect: 'Shifter Wet', label: 'Shifter Wet' },
        { kind: 'knob', slider: 106, expect: 'Loop Point', label: 'Loop Point' },
        { kind: 'toggle', slider: 107, expect: 'Has Samples', label: 'Has Samples' },
        { kind: 'toggle', slider: 109, expect: 'Legacy Tapestop', label: 'Legacy Tapestop' },
        { kind: 'toggle', slider: 110, expect: 'Randomizing Modulator A', label: 'Randomizing Modulator A' },
        { kind: 'toggle', slider: 111, expect: 'Randomizing Modulator B', label: 'Randomizing Modulator B' },
      ],
    },
  ],
};

// Declared but not attributed to any panel (156) -
// mostly parameters the GUI never draws. Review before shipping:
//   slider1: Current speed
//   slider2: Current pattern
//   slider3: Dummy for undo point
//   slider4: Dummy
//   slider5: Dummy
//   slider6: Shuffle amount
//   slider7: Playback enabled
//   slider8: Record enabled
//   slider10: Reset enabled
//   slider12: Dynamic slowdown enabled
//   slider27: Cutoff Start
//   slider28: Cutoff Finish
//   slider30: Morph
//   slider31: Envelope Rise
//   slider32: Envelope Decay
//   slider33: Envelope Sustain
//   slider34: Pitch Shift
//   slider35: Frequency shift
//   slider63: Filter Inertia [ms]
//   slider64: First Pattern
//   slider115: Reset 1-4
//   slider116: Reset 5-8
//   slider117: Reset 9-12
//   slider118: Reset 13-16
//   slider119: Reset 17-20
//   slider120: Reset 21-24
//   slider121: Reset 25-28
//   slider122: Reset 29-32
//   slider123: Slowdown 1-4
//   slider124: Slowdown 5-8
//   slider125: Slowdown 9-12
//   slider126: Slowdown 13-16
//   slider127: Slowdown 17-20
//   slider128: Slowdown 21-24
//   slider129: Slowdown 25-28
//   slider130: Slowdown 29-32
//   slider131: Tape Stop 1-4
//   slider132: Tape Stop 5-8
//   slider133: Tape Stop 9-12
//   slider134: Tape Stop 13-16
//   slider135: Tape Stop 17-20
//   slider136: Tape Stop 21-24
//   slider137: Tape Stop 25-28
//   slider138: Tape Stop 29-32
//   slider139: Retrigger 1-4
//   slider140: Retrigger 5-8
//   slider141: Retrigger 9-12
//   slider142: Retrigger 13-16
//   slider143: Retrigger 17-20
//   slider144: Retrigger 21-24
//   slider145: Retrigger 25-28
//   slider146: Retrigger 29-32
//   slider147: Reverse 1-4
//   slider148: Reverse 5-8
//   slider149: Reverse 9-12
//   slider150: Reverse 13-16
//   slider151: Reverse 17-20
//   slider152: Reverse 21-24
//   slider153: Reverse 25-28
//   slider154: Reverse 29-32
//   slider155: Pitch 1-4
//   slider156: Pitch 5-8
//   slider157: Pitch 9-12
//   slider158: Pitch 13-16
//   slider159: Pitch 17-20
//   slider160: Pitch 21-24
//   slider161: Pitch 25-28
//   slider162: Pitch 29-32
//   slider163: Degrade 1-4
//   slider164: Degrade 5-8
//   slider165: Degrade 9-12
//   slider166: Degrade 13-16
//   slider167: Degrade 17-20
//   slider168: Degrade 21-24
//   slider169: Degrade 25-28
//   slider170: Degrade 29-32
//   slider171: Filter 1-4
//   slider172: Filter 5-8
//   slider173: Filter 9-12
//   slider174: Filter 13-16
//   slider175: Filter 17-20
//   slider176: Filter 21-24
//   slider177: Filter 25-28
//   slider178: Filter 29-32
//   slider179: Gate 1-4
//   slider180: Gate 5-8
//   slider181: Gate 9-12
//   slider182: Gate 13-16
//   slider183: Gate 17-20
//   slider184: Gate 21-24
//   slider185: Gate 25-28
//   slider186: Gate 29-32
//   slider187: Reverb 1-4
//   slider188: Reverb 5-8
//   slider189: Reverb 9-12
//   slider190: Reverb 13-16
//   slider191: Reverb 17-20
//   slider192: Reverb 21-24
//   slider193: Reverb 25-28
//   slider194: Reverb 29-32
//   slider195: Karplus 1-4
//   slider196: Karplus 5-8
//   slider197: Karplus 9-12
//   slider198: Karplus 13-16
//   slider199: Karplus 17-20
//   slider200: Karplus 21-24
//   slider201: Karplus 25-28
//   slider202: Karplus 29-32
//   slider203: Mod FX 1-4
//   slider204: Mod FX 5-8
//   slider205: Mod FX 9-12
//   slider206: Mod FX 13-16
//   slider207: Mod FX 17-20
//   slider208: Mod FX 21-24
//   slider209: Mod FX 25-28
//   slider210: Mod FX 29-32
//   slider211: Filter 2 1-4
//   slider212: Filter 2 5-8
//   slider213: Filter 2 9-12
//   slider214: Filter 2 13-16
//   slider215: Filter 2 17-20
//   slider216: Filter 2 21-24
//   slider217: Filter 2 25-28
//   slider218: Filter 2 29-32
//   slider219: Delay 1-4
//   slider220: Delay 5-8
//   slider221: Delay 9-12
//   slider222: Delay 13-16
//   slider223: Delay 17-20
//   slider224: Delay 21-24
//   slider225: Delay 25-28
//   slider226: Delay 29-32
//   slider227: Chorus 1-4
//   slider228: Chorus 5-8
//   slider229: Chorus 9-12
//   slider230: Chorus 13-16
//   slider231: Chorus 17-20
//   slider232: Chorus 21-24
//   slider233: Chorus 25-28
//   slider234: Chorus 29-32
//   slider235: Freq Shift 1-4
//   slider236: Freq Shift 5-8
//   slider237: Freq Shift 9-12
//   slider238: Freq Shift 13-16
//   slider239: Freq Shift 17-20
//   slider240: Freq Shift 21-24
//   slider241: Freq Shift 25-28
//   slider242: Freq Shift 29-32
//   slider243: Mod A 1-4
//   slider244: Mod A 5-8
//   slider245: Mod A 9-12
//   slider246: Mod A 13-16
//   slider247: Mod A 17-20
//   slider248: Mod A 21-24
//   slider249: Mod A 25-28
//   slider250: Mod A 29-32
