// Generated by tools/jsfx_module_gen.py from C:/Users/Tamura/AppData/Roaming/REAPER/Effects/Saike Tools/Yutani/Saike_Yutani_spidercrab.jsfx
// 189 parameters, 22 panels, 1 unattributed.
//
// HAND: 'Oscillator 2 Shape' moved from OSCILLATOR 1 to OSCILLATOR 2. The
// generator gives a parameter to the first panel that mentions it, and
// OSC1's block reads osc2_shape to decide whether to offer hard sync.
//
// Regenerate rather than hand-editing wholesale, but the few
// corrections below the generator can't make are marked HAND.
import type { ModuleDef } from './modules';
import { isPatched } from './patched';

export const yutaniModule: ModuleDef = {
  title: 'Yutani',
  // Only the patched copy: this module is built on promoted parameters
  // the original does not have.
  match: (n) => isPatched(n) && n.toLowerCase().includes('yutani'),
  groups: ['Source', 'Filter', 'Envelopes', 'Mod & FX'],
  panels: [
    {
      label: 'OSCILLATOR 1',
      group: 0,
      controls: [
        { kind: 'knob', slider: 1, expect: 'Oscillator 1 Gain', label: 'Oscillator 1 Gain', modifiers: [{ kind: 'lfo', slider: 182, expect: 'Amplitude LFO' }, { kind: 'mod', slider: 150, expect: 'Amplitude Mod' }, { kind: 'vel', slider: 114, expect: 'Amplitude Vel' }] },
        { kind: 'knob', slider: 2, expect: 'Oscillator 1 Semitone', label: 'Oscillator 1 Semitone', modifiers: [{ kind: 'lfo', slider: 185, expect: 'Semitones LFO' }, { kind: 'vel', slider: 117, expect: 'Semitones Vel' }] },
        { kind: 'toggle', slider: 3, expect: 'Reset Osc on note', label: 'Reset Osc on note' },
        { kind: 'segmented', slider: 4, expect: 'Oscillator 1 Shape', label: 'Oscillator 1 Shape', options: [{ value: 0, label: 'Saw' }, { value: 1, label: 'Square' }, { value: 2, label: 'Triangle' }, { value: 3, label: 'Fin' }, { value: 4, label: 'PWM' }, { value: 5, label: 'Comb Sa' }, { value: 6, label: 'Comb Sq' }, { value: 7, label: 'SSaw' }, { value: 8, label: 'Glot' }, { value: 9, label: 'WT' }] },
        { kind: 'knob', slider: 80, expect: 'WT1 position', label: 'WT1 position', modifiers: [{ kind: 'lfo', slider: 203, expect: 'Wavetable position LFO' }, { kind: 'mod', slider: 204, expect: 'Wavetable position Mod' }, { kind: 'vel', slider: 205, expect: 'Wavetable position Vel' }] },
        { kind: 'toggle', slider: 95, expect: 'Reset envelope on note', label: 'Reset envelope on note' },
        { kind: 'knob', slider: 193, expect: 'Supersaw Detune / Spread', label: 'Supersaw Detune / Spread' },
        { kind: 'knob', slider: 194, expect: 'Comb Time', label: 'Comb Time' },
        { kind: 'knob', slider: 195, expect: 'Glottis harshness', label: 'Glottis harshness' },
      ],
    },
    {
      label: 'PWM',
      group: 0,
      controls: [
        { kind: 'knob', slider: 50, expect: 'PWM phase', label: 'PWM phase', modifiers: [{ kind: 'vel', slider: 119, expect: 'PWM Phase Vel' }] },
        { kind: 'knob', slider: 51, expect: 'PWM depth', label: 'PWM depth', modifiers: [{ kind: 'vel', slider: 120, expect: 'PWM Depth Vel' }] },
        { kind: 'knob', slider: 52, expect: 'PWM rate', label: 'PWM rate', modifiers: [{ kind: 'vel', slider: 121, expect: 'PWM Rate Vel' }] },
      ],
    },
    {
      label: 'OSCILLATOR 2',
      group: 0,
      controls: [
        { kind: 'segmented', slider: 8, expect: 'Oscillator 2 Shape', label: 'Oscillator 2 Shape', options: [{ value: 0, label: 'Saw' }, { value: 1, label: 'Square' }, { value: 2, label: 'Triangle' }, { value: 3, label: 'Fin' }, { value: 4, label: 'PWM' }, { value: 5, label: 'Comb Sa' }, { value: 6, label: 'Comb Sq' }, { value: 7, label: 'SSaw' }, { value: 8, label: 'Glot' }, { value: 9, label: 'WT' }] },
        { kind: 'knob', slider: 5, expect: 'Oscillator 2 Gain', label: 'Oscillator 2 Gain', modifiers: [{ kind: 'lfo', slider: 183, expect: 'Osc2 Amplitude LFO' }, { kind: 'mod', slider: 151, expect: 'Osc2 Amplitude Mod' }, { kind: 'vel', slider: 115, expect: 'Osc2 Amplitude Vel' }] },
        { kind: 'knob', slider: 6, expect: 'Oscillator 2 Semitone', label: 'Oscillator 2 Semitone', modifiers: [{ kind: 'lfo', slider: 186, expect: 'Osc2 Semitones LFO' }, { kind: 'vel', slider: 118, expect: 'Osc2 Semitones Vel' }] },
        { kind: 'segmented', slider: 7, expect: 'Hard Sync', label: 'Hard Sync', options: [{ value: 0, label: 'Off' }, { value: 1, label: 'On' }] },
        { kind: 'knob', slider: 14, expect: 'Pitch envelope level', label: 'Pitch envelope level', modifiers: [{ kind: 'vel', slider: 110, expect: 'Pitch Envelope Amount Vel' }] },
        { kind: 'knob', slider: 15, expect: 'Pitch Attack', label: 'Pitch Attack', modifiers: [{ kind: 'vel', slider: 111, expect: 'Pitch Attack Vel' }] },
        { kind: 'knob', slider: 16, expect: 'Pitch Decay', label: 'Pitch Decay', modifiers: [{ kind: 'vel', slider: 112, expect: 'Pitch Decay Vel' }] },
        { kind: 'knob', slider: 17, expect: 'Fm level', label: 'Fm level', modifiers: [{ kind: 'lfo', slider: 181, expect: 'FM Level LFO' }, { kind: 'mod', slider: 149, expect: 'FM Level Mod' }, { kind: 'vel', slider: 134, expect: 'FM Level Vel' }] },
        { kind: 'knob', slider: 81, expect: 'WT2 position', label: 'WT2 position', modifiers: [{ kind: 'lfo', slider: 206, expect: 'Pos2 Wavetable position LFO' }, { kind: 'mod', slider: 207, expect: 'Pos2 Wavetable position Mod' }, { kind: 'vel', slider: 208, expect: 'Pos2 Wavetable position Vel' }] },
        { kind: 'toggle', slider: 166, expect: 'Osc2 Pitch Lock', label: 'Osc2 Pitch Lock' },
      ],
    },
    {
      label: 'SUB OSC',
      group: 0,
      enable: { slider: 163, expect: 'Enable Sub Osc' },
      controls: [
        { kind: 'segmented', slider: 47, expect: 'SubOsc Shape', label: 'SubOsc Shape', options: [{ value: 0, label: 'Sine' }, { value: 1, label: 'Odd' }, { value: 2, label: 'Even' }, { value: 3, label: 'Tri' }, { value: 4, label: 'Mud' }] },
        { kind: 'knob', slider: 56, expect: 'Sub oscillator Gain', label: 'Sub oscillator Gain', modifiers: [{ kind: 'lfo', slider: 184, expect: 'Sub Osc Amplitude LFO' }, { kind: 'mod', slider: 161, expect: 'Sub Osc Amplitude Mod' }, { kind: 'vel', slider: 160, expect: 'Sub Osc Amplitude Vel' }] },
        { kind: 'knob', slider: 57, expect: 'Sub oscillator Semi', label: 'Sub oscillator Semi', modifiers: [{ kind: 'lfo', slider: 187, expect: 'Tuning LFO' }, { kind: 'vel', slider: 162, expect: 'Tuning Vel' }] },
        { kind: 'toggle', slider: 164, expect: 'Mix sub in before filter', label: 'Mix sub in before filter' },
      ],
    },
    {
      label: 'NOISE',
      group: 0,
      controls: [
        { kind: 'segmented', slider: 58, expect: 'Noise type', label: 'Noise type', options: [{ value: 0, label: 'Noise' }, { value: 1, label: 'Grating' }, { value: 2, label: 'Digit' }, { value: 3, label: '808' }, { value: 4, label: 'Bell' }] },
        { kind: 'knob', slider: 138, expect: 'Amplitude', label: 'Amplitude', modifiers: [{ kind: 'vel', slider: 141, expect: 'Noise Amplitude Vel' }] },
        { kind: 'knob', slider: 139, expect: 'Decay', label: 'Decay', modifiers: [{ kind: 'vel', slider: 142, expect: 'Noise Decay Vel' }] },
        { kind: 'knob', slider: 140, expect: 'Noise Cutoff', label: 'Noise Cutoff', modifiers: [{ kind: 'vel', slider: 143, expect: 'Noise Cutoff Vel' }] },
        { kind: 'knob', slider: 167, expect: 'Follow', label: 'Follow' },
        { kind: 'toggle', slider: 168, expect: 'Track note pitch', label: 'Track note pitch' },
      ],
    },
    {
      label: 'DRIVE',
      group: 1,
      controls: [
        { kind: 'knob', slider: 26, expect: 'Filter Drive (dB)', label: 'Filter Drive (dB)', modifiers: [{ kind: 'vel', slider: 113, expect: 'Drive Vel' }] },
        { kind: 'knob', slider: 27, expect: 'Post Boost (dB)', label: 'Post Boost (dB)', modifiers: [{ kind: 'vel', slider: 116, expect: 'Output Gain Vel' }] },
      ],
    },
    {
      label: 'FILTER',
      group: 1,
      controls: [
        { kind: 'segmented', slider: 25, expect: 'Filter type', label: 'Filter type', options: [{ value: 0, label: 'Linear' }, { value: 1, label: 'MS-20' }, { value: 2, label: 'Linear x2' }, { value: 3, label: 'Moog' }, { value: 4, label: 'Ladder' }, { value: 5, label: '303' }, { value: 6, label: 'MS-20 asym' }, { value: 7, label: 'DblRes' }, { value: 8, label: 'DualPeak' }, { value: 9, label: 'TriplePeak' }, { value: 10, label: 'svf nl 2p' }, { value: 11, label: 'svf nl 4p' }, { value: 12, label: 'svf nl 2p inc' }, { value: 13, label: 'svf nl 4p inc' }, { value: 14, label: 'rectified resonance' }, { value: 15, label: 'Steiner' }, { value: 16, label: 'SteinerA' }, { value: 17, label: 'Muck' }, { value: 18, label: 'Pill2p' }, { value: 19, label: 'Pill4p' }, { value: 20, label: 'Pill2p Aggro' }, { value: 21, label: 'Pill4p Aggro' }, { value: 22, label: 'Pill2p Stacc' }, { value: 23, label: 'Pill4p Stacc' }, { value: 24, label: 'Ladder3' }, { value: 25, label: 'Ladder6' }, { value: 26, label: 'HLadder' }, { value: 27, label: 'SVF2' }, { value: 28, label: 'SVF4' }] },
        { kind: 'knob', slider: 28, expect: 'Cutoff', label: 'Cutoff', modifiers: [{ kind: 'lfo', slider: 178, expect: 'Cutoff LFO' }, { kind: 'mod', slider: 146, expect: 'Cutoff Mod' }, { kind: 'vel', slider: 98, expect: 'Cutoff Vel' }] },
        { kind: 'knob', slider: 29, expect: 'Resonance', label: 'Resonance', modifiers: [{ kind: 'lfo', slider: 179, expect: 'Resonance LFO' }, { kind: 'mod', slider: 147, expect: 'Resonance Mod' }, { kind: 'vel', slider: 99, expect: 'Resonance Vel' }] },
        { kind: 'knob', slider: 30, expect: 'Morph', label: 'Morph', modifiers: [{ kind: 'vel', slider: 100, expect: 'Morph Vel' }] },
        { kind: 'knob', slider: 41, expect: 'Key Follow', label: 'Key Follow' },
      ],
    },
    {
      label: 'FM',
      group: 1,
      controls: [
        { kind: 'segmented', slider: 37, expect: 'FM mode', label: 'FM mode', options: [{ value: 0, label: 'MIDI sin' }, { value: 1, label: 'MIDI square' }, { value: 2, label: 'Self' }, { value: 3, label: 'Self Abs' }, { value: 4, label: 'Audio Stereo 3/4' }, { value: 5, label: 'Audio Mono 3/4' }] },
        { kind: 'knob', slider: 38, expect: 'FM level', label: 'FM level' },
        { kind: 'knob', slider: 39, expect: 'FM rate factor', label: 'FM rate factor' },
        { kind: 'knob', slider: 40, expect: 'FM spread', label: 'FM spread', modifiers: [{ kind: 'vel', slider: 102, expect: 'FM Spread Vel' }] },
        { kind: 'knob', slider: 42, expect: 'FM Cutoff', label: 'FM Cutoff' },
        { kind: 'knob', slider: 101, expect: 'FM Amount Velocity', label: 'FM Amount Velocity' },
        { kind: 'knob', slider: 148, expect: 'FM Amount Mod', label: 'FM Amount Mod' },
        { kind: 'knob', slider: 180, expect: 'FM Amount Free LFO', label: 'FM Amount Free LFO' },
      ],
    },
    {
      label: 'VOWEL FILTER',
      group: 1,
      controls: [
        { kind: 'knob', slider: 177, expect: 'Free LFO Phase', label: 'Free LFO Phase' },
      ],
    },
    {
      label: 'DISTORTION',
      group: 1,
      enable: { slider: 93, expect: 'Enable Shaper' },
      controls: [
        { kind: 'knob', slider: 48, expect: 'Distortion level [dB]', label: 'Distortion level [dB]' },
        { kind: 'knob', slider: 49, expect: 'Warmth', label: 'Warmth' },
        { kind: 'toggle', slider: 94, expect: 'High gain mode', label: 'High gain mode' },
      ],
    },
    {
      label: 'AMP ENV',
      group: 2,
      controls: [
        { kind: 'knob', slider: 10, expect: 'Amp Accent', label: 'Amp Accent' },
        { kind: 'knob', slider: 11, expect: 'Amp Attack', label: 'Amp Attack', modifiers: [{ kind: 'vel', slider: 106, expect: 'Amp Attack Vel' }] },
        { kind: 'knob', slider: 12, expect: 'Amp Decay', label: 'Amp Decay', modifiers: [{ kind: 'vel', slider: 107, expect: 'Amp Decay Vel' }] },
        { kind: 'knob', slider: 13, expect: 'Sustain level', label: 'Sustain level', modifiers: [{ kind: 'vel', slider: 108, expect: 'Amp Sustain Vel' }] },
        { kind: 'toggle', slider: 97, expect: 'Amp Before Filter', label: 'Amp Before Filter' },
        { kind: 'toggle', slider: 159, expect: 'Use tempo synced envelopes', label: 'Use tempo synced envelopes' },
      ],
    },
    {
      label: 'FILTER ENV',
      group: 2,
      controls: [
        { kind: 'knob', slider: 43, expect: 'Envelope Amount', label: 'Envelope Amount', modifiers: [{ kind: 'vel', slider: 109, expect: '- Amount + Vel' }] },
        { kind: 'knob', slider: 44, expect: 'Cutoff Attack', label: 'Cutoff Attack', modifiers: [{ kind: 'vel', slider: 103, expect: 'Attack Vel' }] },
        { kind: 'knob', slider: 45, expect: 'Cutoff Decay', label: 'Cutoff Decay', modifiers: [{ kind: 'vel', slider: 104, expect: 'Decay Vel' }] },
        { kind: 'knob', slider: 46, expect: 'Cutoff Sustain', label: 'Cutoff Sustain', modifiers: [{ kind: 'vel', slider: 105, expect: 'Sustain Vel' }] },
        { kind: 'knob', slider: 65, expect: 'Cutoff env shape', label: 'Cutoff env shape', modifiers: [{ kind: 'vel', slider: 66, expect: 'Cutoff env shape' }] },
        { kind: 'toggle', slider: 96, expect: 'Cutoff Reset envelope on note', label: 'Cutoff Reset envelope on note' },
      ],
    },
    {
      label: 'CUTOFF LFO',
      group: 2,
      enable: { slider: 135, expect: 'Enable Cutoff LFO' },
      controls: [
        { kind: 'knob', slider: 34, expect: 'Cutoff LFO amount', label: 'Cutoff LFO amount', modifiers: [{ kind: 'lfo', slider: 188, expect: 'Amount LFO' }, { kind: 'mod', slider: 154, expect: 'Amount Mod' }, { kind: 'vel', slider: 130, expect: 'Amount Vel' }] },
        { kind: 'knob', slider: 35, expect: 'Cutoff LFO speed [-]', label: 'Cutoff LFO speed [-]', modifiers: [{ kind: 'lfo', slider: 189, expect: 'Rate LFO' }, { kind: 'mod', slider: 156, expect: 'Rate Mod' }, { kind: 'vel', slider: 131, expect: 'Rate Vel' }] },
        { kind: 'knob', slider: 36, expect: 'Cutoff LFO phase', label: 'Cutoff LFO phase' },
        { kind: 'toggle', slider: 92, expect: 'Cutoff LFO Sync rate to tempo', label: 'Cutoff LFO Sync rate to tempo' },
        { kind: 'toggle', slider: 122, expect: 'Reset LFO on note on', label: 'Reset LFO on note on' },
        { kind: 'knob', slider: 127, expect: 'Cutoff LFO Phase', label: 'Cutoff LFO Phase' },
        { kind: 'knob', slider: 129, expect: 'Cutoff LFO Type', label: 'Cutoff LFO Type' },
      ],
    },
    {
      label: 'MORPH LFO',
      group: 2,
      enable: { slider: 136, expect: 'Enable Morph LFO' },
      controls: [
        { kind: 'knob', slider: 31, expect: 'Morph LFO amount', label: 'Morph LFO amount', modifiers: [{ kind: 'mod', slider: 155, expect: 'Morph LFO Amount Mod' }, { kind: 'vel', slider: 132, expect: 'Morph LFO Amount Vel' }] },
        { kind: 'knob', slider: 32, expect: 'Morph LFO speed [-]', label: 'Morph LFO speed [-]', modifiers: [{ kind: 'mod', slider: 157, expect: 'Morph LFO Rate Mod' }, { kind: 'vel', slider: 133, expect: 'Morph LFO Rate Vel' }] },
        { kind: 'knob', slider: 33, expect: 'Morph LFO phase', label: 'Morph LFO phase' },
        { kind: 'toggle', slider: 91, expect: 'Sync rate to tempo', label: 'Sync rate to tempo' },
        { kind: 'toggle', slider: 123, expect: 'Morph LFO Reset LFO on note on', label: 'Morph LFO Reset LFO on note on' },
        { kind: 'knob', slider: 126, expect: 'Morph LFO Phase', label: 'Morph LFO Phase' },
        { kind: 'knob', slider: 128, expect: 'Morph LFO Type', label: 'Morph LFO Type' },
      ],
    },
    {
      label: 'FEEDBACK',
      group: 2,
      controls: [
        { kind: 'knob', slider: 53, expect: 'Feedback', label: 'Feedback', modifiers: [{ kind: 'vel', slider: 125, expect: 'Feedback Vel' }] },
        { kind: 'toggle', slider: 124, expect: 'Feedback Mode', label: 'Feedback Mode' },
      ],
    },
    {
      label: 'FREE LFO',
      group: 3,
      enable: { slider: 172, expect: 'Enable Free LFO' },
      controls: [
        { kind: 'knob', slider: 59, expect: 'Free LFO amount', label: 'Free LFO amount', modifiers: [{ kind: 'mod', slider: 173, expect: 'Free LFO Amount Mod' }, { kind: 'vel', slider: 174, expect: 'Free LFO Amount Vel' }] },
        { kind: 'knob', slider: 60, expect: 'Free LFO speed [-]', label: 'Free LFO speed [-]', modifiers: [{ kind: 'mod', slider: 175, expect: 'Free LFO Rate Mod' }, { kind: 'vel', slider: 176, expect: 'Free LFO Rate Vel' }] },
        { kind: 'knob', slider: 169, expect: 'Free LFO Type', label: 'Free LFO Type' },
        { kind: 'toggle', slider: 170, expect: 'Free LFO Sync rate to tempo', label: 'Free LFO Sync rate to tempo' },
        { kind: 'toggle', slider: 171, expect: 'Free LFO Reset LFO on note on', label: 'Free LFO Reset LFO on note on' },
      ],
    },
    {
      label: 'PITCH MOD',
      group: 3,
      controls: [
        { kind: 'knob', slider: 9, expect: 'Glide time', label: 'Glide time' },
        { kind: 'knob', slider: 54, expect: 'Vibrato Amount', label: 'Vibrato Amount', modifiers: [{ kind: 'mod', slider: 152, expect: 'Vibrato Amount Mod' }, { kind: 'vel', slider: 144, expect: 'Vibrato Amount Vel' }] },
        { kind: 'knob', slider: 55, expect: 'Vibrato frequency', label: 'Vibrato frequency', modifiers: [{ kind: 'mod', slider: 153, expect: 'Vibrato Frequency Mod' }, { kind: 'vel', slider: 145, expect: 'Vibrato Frequency Vel' }] },
      ],
    },
    {
      label: 'BONUS OSC',
      group: 3,
      enable: { slider: 165, expect: 'Enable Bonus' },
      controls: [
        { kind: 'knob', slider: 18, expect: 'Active Oscs', label: 'Active Oscs' },
        { kind: 'knob', slider: 19, expect: 'Voice 2 [%]', label: 'Voice 2 [%]' },
        { kind: 'knob', slider: 20, expect: 'Detune [semitones]', label: 'Detune [semitones]' },
        { kind: 'knob', slider: 21, expect: 'Voice 3 [%]', label: 'Voice 3 [%]' },
        { kind: 'knob', slider: 22, expect: 'Detune [semitones]', label: 'Detune [semitones]' },
        { kind: 'knob', slider: 23, expect: 'Voice 4 [%]', label: 'Voice 4 [%]' },
        { kind: 'knob', slider: 24, expect: 'Detune [semitones]', label: 'Detune [semitones]' },
        { kind: 'knob', slider: 190, expect: 'Note Mode', label: 'Note Mode' },
        { kind: 'knob', slider: 202, expect: 'Tuning', label: 'Tuning' },
      ],
    },
    {
      label: 'INHARMONIC',
      group: 3,
      enable: { slider: 198, expect: 'Enable Inharmonicity' },
      controls: [
        { kind: 'toggle', slider: 199, expect: 'Snap to harmonic ratios', label: 'Snap to harmonic ratios' },
        { kind: 'knob', slider: 200, expect: 'Inharmonicity', label: 'Inharmonicity' },
      ],
    },
    {
      label: 'FX',
      group: 3,
      controls: [
        { kind: 'knob', slider: 137, expect: 'Analog', label: 'Analog' },
        { kind: 'knob', slider: 158, expect: 'Space', label: 'Space' },
      ],
    },
    {
      label: 'SMEAR',
      group: 3,
      controls: [
        { kind: 'knob', slider: 71, expect: 'AP frequency', label: 'AP frequency' },
        { kind: 'knob', slider: 72, expect: 'AP Feedback', label: 'AP Feedback' },
        { kind: 'knob', slider: 73, expect: 'AP saturation', label: 'AP saturation' },
        { kind: 'toggle', slider: 201, expect: 'Enable allpass stack', label: 'Enable allpass stack' },
      ],
    },
    {
      label: 'OPTIONS',
      group: 3,
      controls: [
        { kind: 'toggle', slider: 62, expect: 'Fix DC', label: 'Fix DC' },
        { kind: 'knob', slider: 63, expect: 'Filter Inertia [ms]', label: 'Filter Inertia [ms]' },
        { kind: 'knob', slider: 64, expect: 'Oversampling', label: 'Oversampling' },
        { kind: 'toggle', slider: 191, expect: 'Perform Amp Correction', label: 'Perform Amp Correction' },
        { kind: 'toggle', slider: 192, expect: 'Legacy Mode', label: 'Legacy Mode' },
        { kind: 'knob', slider: 196, expect: 'Bend range', label: 'Bend range' },
        { kind: 'knob', slider: 197, expect: 'BLEP Type', label: 'BLEP Type' },
      ],
    },
  ],
};

// Declared but not attributed to any panel (1) -
// mostly parameters the GUI never draws. Review before shipping:
//   slider61: fine tune FM
